server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: http://auth-service:8080
              predicates:
                - Path=/api/auth/**,/api/user/**

            - id: profile-service
              uri: http://profile-service:8080
              predicates:
                - Path=/api/profile/**

            - id: post-service
              uri: http://post-service:8080
              predicates:
                - Path=/api/post/**,/api/feed/**

            - id: notification-service
              uri: http://notification-service:8080
              predicates:
                - Path=/api/notification/**